### ISSUE TITLE
template has incorrect peerDependecy for @angular/common = 12.2.16

### ISSUE THREAD

**Issue by bulldog98** [rx-angular/rx-angular#1405]
# Description
yarn notified me about wrong peerDeps (@angular/common 14) for @rx-angular/template
@rx-angular/template: 1.0.0-rc.1 has peerDependency @angular/common 12.2.16

# Tasks to Resolve This

Change the peerDependency to >=12.0.0 analog to how @angular/core is handled

**Comment by mattlocker** [comment]
Same here  with Angular 13 and npm.

**Comment by edbzn** [comment]
It's because there's an import of `@angular/common` in this spec file [for.directive.observable.spec.ts](https://github.com/rx-angular/rx-angular/blob/9ebbe9ac76bcf569f41561a9dc021d2f14fc1777/libs/template/for/src/lib/tests/for.directive.observable.spec.ts#L50), ng-packagr resolves the peer dependency to `"@angular/common": "12.2.16"` in the dist package.json, the question is why it takes spec file dependencies into account.

**Comment by bulldog98** [comment]
In [this ng-packagr Issue](https://github.com/ng-packagr/ng-packagr/issues/2433) there is a similar problem, that seems to stem from @nrwl//angular:package executor

**Comment by LayZeeDK** [comment]
Nx library executors for `build` targets have options to automagically update peer dependencies.

`@rx-angular/template@1.0.0-rc.2` has a pinned version peer dependency on `@angular/common@12.2.16` as seen at https://cdn.jsdelivr.net/npm/@rx-angular/template@1.0.0-rc.2/package.json

**Comment by edbzn** [comment]
The solution is to turn off the `updateBuildableProjectDepsInPackageJson` option for the build target but still can't get why it's taking spec files into account when updating peer deps.
