### ISSUE TITLE
*rxLet directive doesn't trigger for the observables set up later than component rendering

### ISSUE THREAD

**Issue by ysdidenko** [rx-angular/rx-angular#1482]
# Description
*rxLet directive doesn't trigger for the observables set up later than component rendering.

Sometimes we don't have the observable defined straight on a component init. Sometimes we need to assign that later (e.g. fetch some data on demand).

# Steps to Reproduce the Issue
See the example please:
(https://stackblitz.com/edit/angular-ivy-mblqcq?file=src%2Fapp%2Fapp.component.ts)

**Comment by JeanMeche** [comment]
That's pretty much expected, CD doesn't run when you're calling `setTimeout` with `OnPush`. (The component is marked as dirty).

**Comment by hoebbelsB** [comment]
hey @ysdidenko thx for the issue. For cases where you fetch data on-demand I suggest using a `Subject` which you can assign directly to `rxLet` or you introduce a state management solution like `RxState`.

A simple example:

**Template**


```html

<div *rxLet="data$; let data"> {{ data | json }}</div>

```

**Component**

Before

```ts

// before

data$?: Observable<any>;

loadData() {
  this.data$ = fetch();
}

```

With RxState

```ts
// after

state = inject(RxState);
data$ = this.state.select('data');

loadData$ = new Subject();

constructor() {
  this.state.connect('data', this.loadData$.pipe(
     exhaustMap(() => fetch() ),
    // or use switchMap if fits better :)
  ));
}

```

In case of your `setTimeout` example, this could be replaced by:

```ts
data$ = timer(200).pipe(
  switchMap(() => fetch())
)
```


@JeanMeche You are right, but `CD` is actually running, as timers are patched by NgZone, thus triggering a `tick`. The component isn't updated though, because it isn't marked as dirty as you already pointed out.

**Comment by ysdidenko** [comment]
Hi @hoebbelsB , thank you for the suggestion, but:
It helps in a very basic setup like this. Imagine you have not just one observable like this, but multiple ones. Plus using combineLatest, forkJoin, etc. Consider also the nested Observables (very edge case, I know, still..)

In our case it's quite a HUGE refactoring, considering we have a pretty big codebase. 

This works better https://ngrx.io/api/component/LetDirective. However, it doesn't utilize the benefits of what rxAngular was supposed to provide (better performance to less unnecessary change detection). Sad :(

**Comment by hoebbelsB** [comment]
how would it be possible that the directive from `ngrx` is working in that scenario? For this case, there should be no difference at all, because both directives rely on the parent component to run change detection when changing the input.

is it possible that you set up a stackblitz with a comparison?

**Comment by BioPhoton** [comment]
@ysdidenko for your complex scenario we recommend RxState and one of our structural directives in the template package.

@hoebbelsB explained pretty well the case. 

I’ll close it. Feel free to reopen if needed.
