### ISSUE TITLE
How to render a hidden list and display it only when rendered

### ISSUE THREAD

**Issue by boubou158** [rx-angular/rx-angular#1557]
Hi,

I am new to rxAngular and I am not sure to understand fully how to handle this usecase properly.

I would like to benefit from the performance optimization from rxAngular to display huge list of rows and cells

The components are using OnPush strategy.

The problem is that, let's assume I have a child component rows-component and parent-component

rows-component
`<ng-container *rxFor="let row of rows; renderCallback: rowsRendered; strategy: 'immediate'; patchZone: false;">xxx </ng-container>`

which outputs to the parent as soon as the rows are rendered.

and parent-component
`<rows-component [hidden]="!(areRowsRendered$ | async)"></rows-component>`

areRowsRendered$ is a BehaviorSubject and a .next(true) is done when the output from rows-component is received.

The problem is that, to get the [hidden] attribute updated and the list rendered displayed, I need to trigger changedDetector.detectChange() and then I noticed that rows-component rowsRendered is triggered again since the ChangeDetector seems to rerender rows-component. Ending up in bad performance.

Any idea how to solve this? How to hide the list until it is rendered fully and then display it?

Thanks by advance :)

**Comment by boubou158** [comment]
Is there an easy way to check why renderCallBack observable is triggered twice instead of once? I would like to confirm that because of some code issues, rendering does not happen twice instead of once.

**Comment by boubou158** [comment]
I noticed that strategy immediate or userBlocking produces the double renderCallback emission. If I use low strategy, then rendering callback emits once. Is this a bug?

**Comment by hoebbelsB** [comment]
hi @boubou158 thanks for the issue.
In general, your approach looks good to me. If i'm correct, you are facing two issues here:

**[hidden] not properly set**

The reason why `[hidden]` is not rendered in your example is because `async` pipe needs NgZone to run in order to apply any changes. The observable you are connecting to it is probably running outside of angulars zone. You might want to use the `push` pipe or the `rxLet` directive instead. Another solution is to manually set the attribute without relying on change detection. 

**renderCallback emitting twice**

I cannot see any reason why the `renderCallback` is emitting multiple times in your example. I can only randomly guess that it's may be related to a missing `trackBy` function. If you could provide a stackblitz with a reproduction of the issue, I can try to help you out more
