### ISSUE TITLE
Make the state readonly

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#1617]
I work with people who are not so smart, and they intend to make mistakes even though I explain to them.

For example:

```
loadSomething() {
   this.get().accounts = null;
   ...
}
```
The problem with that code, the state is changing unexpectedly and not by the rx-state flow (`connect`, `hold`), because of the rx-state reactivity. and because I get the actual state, I can change that because it references to the origin source.

The solution to prevent that is to make the state read-only. 

I want to prevent them to do that mistake. in Redux/ngrx the state is read-only.

**Comment by edbzn** [comment]
Related to #1449, we should make it readonly with types, not runtime lock.

**Comment by edbzn** [comment]
Fixed by #1618, thanks for raising this.

**Comment by jon9090** [comment]
Thanks, @edbzn ! When will the new version be released so that I can start using it?

**Comment by edbzn** [comment]
@jon9090 We just published the v16.1.0 release.

**Comment by edbzn** [comment]
Bad news @jon9090, we just reverted these changes as it was breaking some applications and we haven't anticipated that. We are now discussing introducing again the change in v17 but we are still not sure.

**Comment by jon9090** [comment]
@edbzn Well, the idea is to use the API that RxState provides such `set` or `connect` or `hold` right? 

What is good is when I can get the state and make some changes directly in anticipation way in my application flow.

I would tell them to fix that issue because, in the first place, they do something not by the best practices.

**Comment by edbzn** [comment]
Yes, mutating the get return or the projection function is a bad practice, that's why we agreed on introducing the readonly type. What we hadn't anticipated is that it breaks applications that expect `RxState.get` to return `T`, not `readonly T`, it can result on tsc errors, particularly on arrays, so we can't release this as a minor change as we did. What you can do to prevent such usage is to write an ESLint rule to prevent that.
