### ISSUE TITLE
Virtual scroll: positioning issues when the input array updates while virtual scroll is rendering 

### ISSUE THREAD

**Issue by FelixMuehling** [rx-angular/rx-angular#1746]
# Description

When the input array updates while the virtual scroll is still rendering, the items don't get positioned correctly.

# Steps to Reproduce the Issue

See [stackblitz](https://stackblitz.com/edit/rx-angular-virtual-scroll-positioning-issue?file=src%2Fmain.ts).

The reproduction app is rendering 200 items initially and updates the array after 100ms.

To reproduce the bug, reload the page (not stackblitz but the App on the right) and repeat it until the positioning of the items is off.

It does only occurs when the update happens while virtual scroll is still working on/rendering the old data. You can either reduce the time in the setTimeout call on line 47, or throttle your CPU using the DevTools (Chrome: `Performance` -> Settings icon on the top right -> CPU: 6x slowdown).

I have throttled my CPU with 6x slowdown to consistently reproduce it.

I have subscribed to the `renderedCallback` subject to see when the rendering completed, and the bug seems to only occur when I update the signal before the current items are rendered.

# Environment

- angular 18.1.1
- rx-angular/template 18.0.2

See [stackblitz](https://stackblitz.com/edit/rx-angular-virtual-scroll-positioning-issue?file=src%2Fmain.ts).

**Comment by rozpuszczalny** [comment]
Just adding some findings on that one, since I'm experiencing similar issues (yet I cannot create shareable reproduction steps).

(render) `strategy` plays a role here. When `native` is used, which is a strategy without scheduling, I cannot reproduce this issue at all. However, if I use any strategy with scheduling (even `local` and `global`), then it is reproducible (usually with x6 CPU slowdown).

Here's the screenshot of an example misplacement

![image](https://github.com/user-attachments/assets/b1e8c560-fe8c-4c94-8cde-04db6a231b78)

Usually, such a misplacement is gone after scrolling past that faulty item.

In my case (for which I don't have a reproduction repo), any of ConcurrentStrategies results in misplacements (e.g. the first item becomes second, the second item becomes first), whereas using any of BasicStrategies seems to solve the issue.

So I suspect there is some kind of a race condition, which results in misplacements.

**Comment by hoebbelsB** [comment]
thank u very much for all the input. Had some very busy days. Will investigate this week!

**Comment by hoebbelsB** [comment]
hey @FelixMuehling can u please confirm the issue is gone, when not using a static value binding, but a reactive one? (passing the signal as signal, not reading it's value in the template).

![image](https://github.com/user-attachments/assets/68999442-d2e6-4848-80b5-ea85d4c936e7)

**Comment by hoebbelsB** [comment]
the virtual scroller branches out and behaves a bit different when receiving a static value. I might just refactor this section.

**Comment by FelixMuehling** [comment]
> hey @FelixMuehling can u please confirm the issue is gone, when not using a static value binding, but a reactive one? (passing the signal as signal, not reading it's value in the template).

That doesnt seem to make a difference. Im still able to easily reproduce it.

![image](https://github.com/user-attachments/assets/c84990cc-8d32-4d65-99bf-a578b3ed5343)

**Comment by hoebbelsB** [comment]
thank u :)

**Comment by hoebbelsB** [comment]
hey @FelixMuehling just a heads-up - I didn't forget you :D Figured out what the issue is, will come up with a PR very soon. It's a race condition between the resize observer and the positioning

**Comment by FelixMuehling** [comment]
Sounds great :) I appreciate your work

**Comment by hoebbelsB** [comment]
ha, finally got there :) figured out the issue and came up with a fix for it. Btw. if your solution is not requiring the resize observer, just turn it off with the `withResizeObserver` flag ;)

**Comment by hoebbelsB** [comment]
ha, finally got there :) figured out the issue and came up with a fix for it. Btw. if your solution is not requiring the resize observer, just turn it off with the `withResizeObserver` flag ;)

**Comment by FelixMuehling** [comment]
Just tested the new release and its now working properly :+1: 

thank you :)
