### ISSUE TITLE
RxEffects

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#293]
# Problem Solved By The Feature

Often people just introduce RxState to hold a side effect. For those, we can provide a standalone `RxEffects` service.

```typescript
constructor(private state: RxState<any>) {
    this.state.hold(this.sideEffect$)
  }
```

# Solution

```typescript
constructor(private rxEf: RxEffects) {
    this.rxEf.hold(this.sideEffect$)
}
```

Possible Extensions:
- Take Subscriptions
- Take A takeUntilTrigger/operatorFunction 
- Return the subscription

# Additional Context

Here we could take it as a chance to explore more archetypes and use cases.
Also, e.g. `ionic` lifecycles could get considered too! 

# Related 

#423

**Comment by Karnaukhov-kh** [comment]
This looks nice. But is it enough to justify separate service? Maybe we can iterate over this idea and introduce some additional effects-related functionality? (nothing in mind right now 😅)

**Comment by BioPhoton** [comment]
Exactly what I was thinking!

**Comment by BioPhoton** [comment]
Ideas:

- Return the subscription
- Option to pass a "takeUntil" trigger

**Comment by hoebbelsB** [comment]
> Ideas:
> 
>     * Return the subscription
> 
>     * Option to pass a "takeUntil" trigger

Maybe even take a subscription?

Where do you want to put the takeUntil trigger? Inside the `hold` method? I think this could be very useful in order to have code separated more clearly. Also, I often use take(1) or something inside the trigger for an effect. The hold method could take an `operatorFunction` aswell:

*before*
```ts
const trigger$ = myTrigger$.pipe(take(1));
const effect = triggerVal => doSomething(triggerVal);
state.hold(trigger$, effect);
```

*after*
```ts
const trigger$ = myTrigger$.pipe(take(1));
const effect = triggerVal => doSomething(triggerVal);
const until$ = take(1);
state.hold(trigger$, effect, until$);
```

**Comment by BioPhoton** [comment]
> Maybe even take a subscription?

Nice!

**Comment by mhamri** [comment]
@BioPhoton 

> Often people just introduce RxState to hold a side effect. 

what is the meaning of holding an rxjs without binding it to any action? is it only for subscription handling? if that's the case, should the rxState bother doing that? it's nothing to do with state management and can be handled esaily with many different methods.

also, I was reading the #423  and I'm trying to understand how this solution will solve that problem, in my understanding of that issue, the user wanted to have something similar to what ngrx provides

```
const trigger$ = myTrigger$.pipe(tap(console.log));
const sideEffectFn=this.state.effect(trigger$);
sideEffectFn(); //should print 1 in console. 
```

so in my understanding, it should return a function that will cause the `$trigger` to be called, not the otherwise. 

`hold`: will call a side effect when the stream has some value
`effect` will trigger the stream when a side effect is called. 

though it's already achievable by combining `select` and `hold`

**Comment by BioPhoton** [comment]
I understand. But imperative side effects end up so easily in a race condition that I'm not really amused to release it. 
Furthermore, the solution where we handle the potential race condition is a kill dissonant for me.

"I want to provide imperative APIs, but i have to handle racecondition still with switchMap inside" an at least for me hard to reason code structure. 

I updated the above with our latest findings.

**Comment by wizardnet972** [comment]
Can RxState reduce boilerplate when creating effects? 

I mean to create effect I need to create a new `Subject` and then write my logic in the `pipe` and create another function to trigger the subject:

```
 readonly loadSomething$ = new Subject();
 
 loadSomethingEffect$ = this.hold(
   this.loadSomething$.pipe( .... )
 )
 
 loadSomething() {
   this.loadSomething$.next();
 }
```

Consider I have a 10 actions (subjects) with their logic inside the pipe... it's hard to tell where the subjects are triggered by `hold` function.

So can RxState reduce boilerplate when creating effects by provide a trigger function that return the subject?

Something like that will be much readable and cleaner way:

```
 readonly loadSomethingEffect$ = this.effect<LoadSomethingInput>((input$) =>
    input$.pipe(...)
 );
...
loadSomethingEffect$.next(..);
```

What do you think about it? no need to have `Subject`, one function handles the logic

**Comment by mhamri** [comment]
@wizardnet972 not sure if it's against the best practice or not, but why not use it like this? 

```
constructor(private state:RxState<SomeState>){
    state.effect(state.select('somevaiable'), ()=> console.log('stateChanged'));
}

onClick(){
    this.state.set('somevariable', false);
}
```

**Comment by wizardnet972** [comment]
@mhamri what you suggesting is to update the store and then do something. sometimes I don't want and don't need to update the store in order to make something happen.

consider you need to save the form and submit it to the server (http) and then after show notification. In this case, I can't update the store and show the notification. I end up with a complex store.

I want to subscribe to subject and when the subject is triggered then do something. the problem `hold` try to resolve is to subscribe to whatever observable and do something after.

My question is can I get it with one function just like `effect` in ngrx component store? because keeping the subject and the pipe apart is difficult to handle.
