### ISSUE TITLE
Autoapply classes for RxViewContext states

### ISSUE THREAD

**Issue by BioPhoton** [rx-angular/rx-angular#297]
# Problem Solved By The Feature

Sometimes we want to style the content differently depending on the reactive context.
ATM, it is only possible very clumsy.

# Solution

Add class names for the different states to the dom:
- suspense
- next
- error
- complete

Maybe also the directive name:
- rx-let
- rx-if
- ...

**Comment by hoebbelsB** [comment]
this is a very good idea, so does the cdk. But how would you want to add those classes to the nativeElement? This could be a bit tricky, since the `LetDirective` often sits on a `ng-container` element. And which element does the `PushPipe` applies it's class to? Or is it just for structural directives?

**Comment by BioPhoton** [comment]
Where is it used in material?

**Comment by BioPhoton** [comment]
Close it as not needed
