### ISSUE TITLE
connect vs hold

### ISSUE THREAD

**Issue by jon9090** [rx-angular/rx-angular#966]
Hi @BioPhoton thank you for this great library.

Can you please share example of login process with rx-angular? because I have been confuse about using `connect` vs `hold`.

hold - is for side effects right? so my side effect is calling to http.. but since `hold` doesn't return anything and the login process should update the store: `pending`, `error`, `user`, `token` and so on.. how I do it with clean flow?

for example with connect is easy and clear code structure:
```
 this.connect(
   ...
   switchMap(() => this.http.get('......login')),
   map(user => user),
   startWith({ pending: true, error: null }),
   endWith({ pending: false })
 );
```

But with hold it's using `this.set` and tap functions.. 

So which operator should I use to handle login flow? can you provide an example please?

**Comment by hoebbelsB** [comment]
your solution is totally fine. I would consider this as suggested solution. Since your http calls results in a state-change, it is technically no side-effect. side-effects happen without changing the state. They can be triggered by state changes though.

```ts
this.connect(
   this.loginTrigger$.pipe(exhaustMap(() => this.http.get('......login').pipe(
     map(user => user),
     startWith({ pending: true, error: null }),
     endWith({ pending: false })
   ))),
 );
```

this way you don't over-emit the login request when someone hammers the login button :D

**Comment by jon9090** [comment]
@hoebbelsB thank you!
